### ISSUE TITLE
Code review and feedback

### ISSUE THREAD

**Issue by j4asper** [j4asper/dmr.py#3]
Hi! I have made this python library, and i want some feedback on the code itself. There is probably a lot of stuff that i don't know, that would make the code a lot more clean. This is the first time that i am writing a python library, therefore i would like to get some feedback to improve.

Thank you.

**Comment by Boxap** [comment]
Hi @j4asper,

So, I haven't  thoroughly analyzed _every_ line of code you have, but there is some little points which I noticed:

### 1. Exceptions
Example:
https://github.com/j4asper/dmr.py/blob/97d9b3935ec25cfc302f50e8ee3e83e680938376/dmr/main.py#L79

Basically it's not a good practice to use base class `Exception` like that. It's not really informative and can cause some issues handling it.
I would consider to use some subclass of Exception. You even can implement some custom exception, although I don't see really need for it here

### 2. `== None`

Example:
https://github.com/j4asper/dmr.py/blob/97d9b3935ec25cfc302f50e8ee3e83e680938376/dmr/main.py#L78

According to [PEP-8](https://peps.python.org/pep-0008/#programming-recommendations):
> Comparisons to singletons like None should always be done with is or is not, never the equality operators.



### 3. Creation of new instances of DMR inside DMR

https://github.com/j4asper/dmr.py/blob/97d9b3935ec25cfc302f50e8ee3e83e680938376/dmr/main.py#L11-L45

I do not really understand logic behind this approach. Do you **really** need to return new instances of `DMR` out of already created instance?

- If you really need to create multiple `DMR`s I would place this logic into separate function or class
- If you don't need new objects you can just assign extracted parameters to already instantiated `DMR` object as attributes
- If you don't need new objects but for some reason want to return `DMR` from this method you can just return `self`

by the way this method right now can (should) just be a `@staticmethod`

### 4. Union[x, None]

Example:
https://github.com/j4asper/dmr.py/blob/97d9b3935ec25cfc302f50e8ee3e83e680938376/dmr/main.py#L133

You can just use `typing.Optional`

From `typing` [documentation](https://docs.python.org/3/library/typing.html):
> Optional[X] is equivalent to X | None (or Union[X, None]).


### 5. value in list

Example:
https://github.com/j4asper/dmr.py/blob/45408d295a62b468be343f25a72ad484c3b450db/dmr/utils/clean_data.py#L17

Just use
`if key in ["fuel_consumption", "electricity_consumption", "battery_capacity", "electric_range"]`


### 6. `clean_data` and `extract_data` inconsistency 

Seems like you have similar "data cleaning" functionality in `clean_data` and `extract_data`

Example:

https://github.com/j4asper/dmr.py/blob/45408d295a62b468be343f25a72ad484c3b450db/dmr/utils/extract_data.py#L43

https://github.com/j4asper/dmr.py/blob/45408d295a62b468be343f25a72ad484c3b450db/dmr/utils/clean_data.py#L11-L13

It's better to have these "same level of abstraction" transformations in one place, not scattered between different files

### 7. `clean_data`

Your `clean` function is pretty hard-to-read right now

Regarding `key` cleaning you might want to work with them directly, for example instead of 
https://github.com/j4asper/dmr.py/blob/45408d295a62b468be343f25a72ad484c3b450db/dmr/utils/clean_data.py#L4-L7

just
`data["insurance"]["created"] = datetime.strptime(data["insurance"]["created"], "%d-%m-%Y")`

**But most likely cleaner way would be** to move all functionality to the `extract_data`, where you already doing some data transformation for every field. Probably it would be better to create several little functions for every field rather then trying to describe all transformation in every line there

### 8 . "Magic values" in `extract_data`

Example:
https://github.com/j4asper/dmr.py/blob/650ef35b0497c829bfbd8a089065562d61605393/dmr/utils/extract_data.py#L4

You might want to store these `/html/body/div[2]/div/div[1]...` xpath strings in some data structure
That will have two benefits:

1.  Readability.
Line like 
`data["vin"] = source.xpath(xpath_strings["vin"])[0].text_content()`
looks much cleaner (but think about better naming, `xpath_strings` is pretty bad I guess)
2.   If something changes on these html's in the future you will be able to change  these strings centralized (maybe even just by passing new dictionary)


And for the love of god
https://github.com/j4asper/dmr.py/blob/650ef35b0497c829bfbd8a089065562d61605393/dmr/utils/extract_data.py#L5

Newlines are free, don't try to create megaline saving 2 newlines

(by the way you don't need `lower()` if you use `capitalize()` after that)

### P.S.
Judging by your usage implementation of `DMR` and `Insurance` classes you might want to take a look on [pydantic](https://pydantic-docs.helpmanual.io) or [dataclasses](https://docs.python.org/3/library/dataclasses.html)

-----------------------------------

I'm pretty tired so I guess that's all from my side for today.
I've seen not all the code, but I guess that's still something (I can take additional look later, if you'll be interested)

Hope this will help.

**Comment by j4asper** [comment]
Thank you very much for your time, I will redo all of this to improve the codebase. It was very helpful.
